### ISSUE TITLE
Can't auto-modify release note excel when the build ID version isn't 0000.

### ISSUE THREAD

**Issue by Nathan-Lin-NL** [Kevin-Liou/HpBIOSReleasePkg#10]
Debug message for you reference.

================================Modify Pkg Update Version=================================
Can't find release note file.
ReleaseNote_xlsm['Arya_PV_S11_BIOS_Release_Note_021800.xlsm', '~$Arya_PV_S11_BIOS_Release_Note_021800_0002.xlsm']
Modify Arya_PV_S11_021801 Pkg Version (.nsh & .bat) to 021801 succeeded.

**Comment by Kevin-Liou** [comment]
commit f8ec945ca62ad5957d17b953f82a6e1a7f154cc2 fix, please retest v4.8.15

**Comment by Kevin-Liou** [comment]
Confirm it's fixed.
