### ISSUE TITLE
U23 couldn't use release tool to generate bios PKG

### ISSUE THREAD

**Issue by Scott-lin0518** [Kevin-Liou/HpBIOSReleasePkg#11]
![image](https://github.com/Kevin-Liou/HpBIOSReleasePkg/assets/82068654/2c12712e-bf03-4a7d-a030-1681394bce36)

**Comment by Scott-lin0518** [comment]
Nathan would have this issue fixed right.

**Comment by Scott-lin0518** [comment]
This issue is caused by last one release tool naming problem, so change file from .nupkg to .zip U23 PKG name would miss one ".".
With this problem would cause run release tool fail.

So close this issue.

**Comment by Kevin-Liou** [comment]
96074997f193a3dfdab230f1b27e261151718f59 fix this issue, please retry v4.8.17
